# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742
print('The diameter of {planet} is {measure} kilometers'.format(planet="Earth", measure=12742.34))

The diameter of Earth is 12742.34 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd
 
data = {
  "TotalScore": [420, 380, 390],
  "MathScore": [50, 40, 45]
}
 
#load data into a DataFrame object:
df = pd.DataFrame(data)
 
print(df)

   TotalScore  MathScore
0         420         50
1         380         40
2         390         45


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime

import pandas as pd
 
test_date = datetime.datetime.strptime("01-7-2022", "%d-%m-%Y")
K = 41
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-07-2022', '02-07-2022', '03-07-2022', '04-07-2022', '05-07-2022',
       '06-07-2022', '07-07-2022', '08-07-2022', '09-07-2022', '10-07-2022',
       '11-07-2022', '12-07-2022', '13-07-2022', '14-07-2022', '15-07-2022',
       '16-07-2022', '17-07-2022', '18-07-2022', '19-07-2022', '20-07-2022',
       '21-07-2022', '22-07-2022', '23-07-2022', '24-07-2022', '25-07-2022',
       '26-07-2022', '27-07-2022', '28-07-2022', '29-07-2022', '30-07-2022',
       '31-07-2022', '01-08-2022', '02-08-2022', '03-08-2022', '04-08-2022',
       '05-08-2022', '06-08-2022', '07-08-2022', '08-08-2022', '09-08-2022',
       '10-08-2022'],
      dtype='object')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
print(lists)

[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
